name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            libncurses6 \
            libstdc++6 \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev

      - name: Install Buildozer
        run: pip install buildozer

      - name: Build APK
        working-directory: paradise/paradise
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Paradise-APK
          path: paradise/paradise/bin/*.apk
